config/routes.rb
Rails.application.routes.draw do
  resources :gifts
  get 'welcome/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gifts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = open(auth.info.image.gsub("http","https")) # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = current_user.gifts#Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)
    @user = current_user
    @gift.user_id = @user.id
    @og = OpenGraph.new(@gift.url)
    @gift.title = @og.title
    @gift.description = @og.description
    @gift.image = open(@og.images.first)
    

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:url, :user_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gifts</h1>

<table>
  <thead>
    <tr>
      <th> </th>
      <th>Item</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= image_tag gift.image.url(:thumb) %></td>
        <td><%= link_to gift.title, gift.url %></td>
        <td><%= gift.user.name %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New Gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @gift.url %>
</p>
<p>
  <strong> <%= @gift.title %></strong>
 <%= @gift.description %>
 <%= image_tag @gift.image.url(:medium) %>
</p>

<p>
  <strong>User:</strong>
  <%= @gift.user %>
</p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<% if !user_signed_in? %>
<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<% else %>
Welcome <%= current_user.name %>, <%= link_to "Log Out", destroy_user_session_path, :method => :delete  %></br>
<%= link_to "View my list", gifts_path %> | <%= link_to "Add Item", new_gift_path %>
<% end %>